= John Doe - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Project - Level 4

---

== Overview

Project - Level 4 is a desktop project application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the ability to list all tasks and projects*
** What it does: Allows the user to list all tasks and projects and switch between panels after sorting or finding a specific task/project
** Justification: This feature helps in navigating the program as well as to allow ease of use.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.

* *Minor enhancement*: added a remove tag feature which removes a specific tag from all tasks

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Added a remove task feature and a feature to convert the deadline type to Date (from string)
** Documentation:
*** Did readability changes making the userguide more reader friendly
** Community:
*** PRs reviewed

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

==== List projects: `listprojects`
Lists all projects, is also used to switch back to project list from task list.

* Format: `listproject`
* Alias: `lp`, i.e. `listproject` is equivalent to `lp`

Outcome: Project Box (Panel C) will will display all projects within project list.


=== Listing all tasks: `list`
Lists all tasks in the current project. Can also be used to show all tasks after finding a specific tasks

* Format: `list`

* Alias: `l`, i.e. `list` is equivalent to `l`

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=list]

include::../DeveloperGuide.adoc[tag=removetags]

